# HP Group Analysis

Creatures with identical actual HP in the same CR tier, but different predicted HP.
The prediction spread reveals which features drive the differences — and which costs may need tuning.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
# Resolve data directory relative to this notebook's location
NOTEBOOK_DIR = Path.cwd()

# Walk up until we find the data/ directory
for _candidate in [NOTEBOOK_DIR, NOTEBOOK_DIR / '..', NOTEBOOK_DIR / '../..']:
    if (_candidate / 'data' / 'engineered_features.csv').exists():
        DATA_DIR = str(_candidate / 'data')
        break
else:
    DATA_DIR = './data'

df = pd.read_csv(DATA_DIR + '/engineered_features.csv')
contributions_df = pd.read_csv(DATA_DIR + '/feature_contributions.csv')

print(f'Loaded {len(df)} creatures, {len(contributions_df)} contribution rows')

Loaded 324 creatures, 324 contribution rows

In [3]:
# For cr3 (CR 5-10), group creatures within 2 HP of each other.
# For other tiers, use exact HP match.
HP_PROXIMITY = 2
MIN_GROUP_SIZE = 5

def find_hp_groups(df, tier, proximity=0):
    """Find groups of creatures with similar HP in a tier."""
    tier_df = df[df['cr_tier'] == tier].sort_values('actual_hp').copy()
    
    if proximity == 0:
        # Exact match
        tier_df['hp_group'] = tier_df['actual_hp']
    else:
        # Cluster creatures within `proximity` HP of each other
        groups = []
        group_id = 0
        group_min_hp = None
        for _, row in tier_df.iterrows():
            hp = row['actual_hp']
            if group_min_hp is None or hp - group_min_hp > proximity:
                group_id += 1
                group_min_hp = hp
            groups.append(group_id)
        tier_df['hp_group'] = groups
    
    return tier_df

# Build groups for all tiers
all_groups = []
for tier in ['cr1', 'cr2', 'cr3', 'cr4', 'cr5']:
    proximity = HP_PROXIMITY if tier == 'cr3' else 0
    tier_df = find_hp_groups(df, tier, proximity)
    
    for gid, gdf in tier_df.groupby('hp_group'):
        if len(gdf) >= MIN_GROUP_SIZE:
            hp_min, hp_max = int(gdf['actual_hp'].min()), int(gdf['actual_hp'].max())
            hp_label = str(hp_min) if hp_min == hp_max else f'{hp_min}-{hp_max}'
            all_groups.append({
                'cr_tier': tier,
                'hp_label': hp_label,
                'hp_min': hp_min,
                'hp_max': hp_max,
                'count': len(gdf),
                'names': gdf['Name'].tolist(),
                'pred_range': gdf['predicted_hp'].max() - gdf['predicted_hp'].min(),
            })

groups = pd.DataFrame(all_groups).sort_values('pred_range', ascending=False)
print(f'{len(groups)} groups found\n')
groups[['cr_tier', 'hp_label', 'count', 'pred_range']].round(1)

20 groups found

   cr_tier hp_label  count  pred_range
19     cr3  136-138      7        68.2
14     cr2       45     10        64.7
18     cr3  126-127      7        57.4
11     cr2       22      6        46.3
17     cr3  110-112      6        39.8
15     cr2       52     10        38.6
13     cr2       33      5        31.7
12     cr2       27      5        28.0
8      cr1       13     11        24.6
7      cr1       11     12        22.6
9      cr1       19      9        21.4
10     cr1       22     17        20.1
16     cr2       59      5        19.5
6      cr1        9      5        15.8
0      cr1        1     11        12.6
4      cr1        5      6        12.3
5      cr1        7      5        11.9
1      cr1        2      6         6.4
2      cr1        3      5         5.7
3      cr1        4      5         4.7

In [4]:
# Phase 2 columns to always show
phase2_cols = [
    'ac_deviation', 'attack_deviation', 'dpr_deviation', 'save_dc_deviation',
    'has_advantage_condition', 'has_disadvantage_condition',
    'has_attackers_advantage', 'inflicts_prone'
]

# Resistance/immunity columns
resist_immun_cols = ['resistance_count', 'immunity_count']

# Feature flag columns (feature_*) and contribution columns (contrib_*)
feature_flag_cols = [c for c in df.columns if c.startswith('feature_') and c not in ['feature_hp', 'feature_dpr', 'feature_ac', 'feature_attack']]
contrib_cols = [c for c in contributions_df.columns if c.startswith('contrib_')]

def build_group_df(names):
    """Build a comparison dataframe for a list of creature names."""
    group = df[df['Name'].isin(names)].sort_values('predicted_hp')
    names_sorted = group['Name'].tolist()
    
    # Start with core prediction columns
    core = ['Name', 'actual_hp', 'predicted_hp', 'hp_delta']
    result = group[core].copy()
    
    # Add phase 2 columns that vary
    for col in phase2_cols:
        if col in group.columns and group[col].nunique() > 1:
            result[col] = group[col].values
    
    # Add resistance/immunity counts that vary
    for col in resist_immun_cols:
        if col in group.columns and group[col].nunique() > 1:
            result[col] = group[col].values
    
    # Add feature flags that vary within the group
    for col in feature_flag_cols:
        if col in group.columns and group[col].nunique() > 1:
            result[col.replace('feature_', 'f_')] = group[col].values
    
    # Add non-zero contribution columns that vary
    group_contribs = contributions_df[contributions_df['Name'].isin(names_sorted)]
    if len(group_contribs) > 0:
        group_contribs = group_contribs.set_index('Name').loc[names_sorted]
        for col in contrib_cols:
            if col in group_contribs.columns:
                vals = group_contribs[col]
                if vals.abs().max() > 0.5 and vals.nunique() > 1:
                    result[col] = vals.values
    
    result = result.set_index('Name')
    return result.round(1)

print(f'Ready — {len(feature_flag_cols)} feature flags, {len(contrib_cols)} contribution cols')

Ready — 91 feature flags, 0 contribution cols

In [5]:
# Generate one dataframe per group, sorted by prediction range (most spread first)
for _, row in groups.iterrows():
    tier, hp_label, count = row['cr_tier'], row['hp_label'], int(row['count'])
    print(f'\n{"="*80}')
    print(f'{tier} | actual_hp={hp_label} | {count} creatures | pred range: {row["pred_range"]:.1f} HP')
    print(f'{"="*80}')
    display(build_group_df(row['names']))

================================================================================
cr3 | actual_hp=136-138 | 7 creatures | pred range: 68.2 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,resistance_count,immunity_count,f_amphibious,f_angelic_weapons,f_breath_weapon,f_damage_absorption,f_false_appearance,f_innate_spellcasting,f_magic_resistance,f_shapechange,f_siege_monster,f_stench
Name,,,,,,,,,,,,,,,,,,,
Shambling Mound,136,118.9,-17.1,0.0,0.0,-9.0,-1.0,2,1,0,0,0,1,0,0,0,0,0,0
Hezrou,136,136.7,0.7,6.0,0.0,-16.0,-1.0,5,1,0,0,0,0,0,0,1,0,0,1
Young Green Dragon,136,139.3,3.3,7.0,0.0,4.3,-1.0,0,1,1,0,1,0,0,0,0,0,0,0
Tyrannosaurus Rex,136,149.4,13.4,-2.0,3.0,0.5,2.0,0,0,0,0,0,0,0,0,0,0,0,0
Frost Giant,138,159.4,21.4,2.0,2.0,-2.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0
Deva,136,172.7,36.7,4.0,-1.0,-14.0,0.0,3,0,0,1,0,0,0,1,1,1,0,0
Treant,138,187.1,49.1,0.0,2.0,-26.0,0.0,2,0,0,0,0,0,1,0,0,0,1,0

================================================================================
cr2 | actual_hp=45 | 10 creatures | pred range: 64.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_disadvantage_condition,inflicts_prone,resistance_count,...,f_etherealness,f_horrifying_visage,f_incorporeal_movement,f_keen_senses,f_life_drain,f_pack_tactics,f_possession,f_rampage,f_spider_climb,f_sunlight_sensitivity
Name,,,,,,,,,,,,,,,,,,,,,
Ghost,45,10.9,-34.1,-3.0,-1.0,-11.0,-1.0,0,0,6,...,1,1,1,0,0,0,1,0,0,0
Silver Dragon Wyrmling,45,12.3,-32.7,8.0,1.0,1.3,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Centaur,45,38.6,-6.4,-1.0,1.0,16.5,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Rhinoceros,45,46.4,1.4,-2.0,2.0,-3.0,2.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Hunter Shark,45,47.1,2.1,-1.0,5.0,-4.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Giant Hyena,45,51.1,6.1,0.0,0.0,0.0,0.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Merrow,45,52.1,7.1,0.0,1.0,0.5,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Hell Hound,45,65.8,20.8,2.0,1.0,0.7,-1.0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
Wight,45,67.4,22.4,1.0,-1.0,3.0,0.0,1,0,3,...,0,0,0,0,1,0,0,0,0,1
Ochre Jelly,45,75.6,30.6,-5.0,-1.0,-4.5,0.0,0,0,1,...,0,0,0,0,0,0,0,0,1,0

================================================================================
cr3 | actual_hp=126-127 | 7 creatures | pred range: 57.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_advantage_condition,has_disadvantage_condition,inflicts_prone,resistance_count,immunity_count,f_amphibious,f_blood_frenzy,f_breath_weapon,f_charge,f_rejuvenation,f_siege_monster,f_spellcasting,f_terrain_camouflage
Name,,,,,,,,,,,,,,,,,,,,
Earth Elemental,126,84.7,-41.3,2.0,1.0,-7.0,0.0,0,0,0,3,1,0,0,0,0,0,1,0,0
Medusa,127,115.1,-11.9,0.0,-2.0,-11.5,-1.0,0,0,0,0,0,0,0,0,0,0,0,0,0
Young Black Dragon,127,120.8,-6.2,7.0,0.0,13.3,-1.0,0,0,0,0,1,1,0,1,0,0,0,0,0
Giant Shark,126,121.4,-4.6,-2.0,6.0,-12.5,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0
Mammoth,126,121.5,-4.5,-2.0,3.0,-2.3,3.0,0,0,1,0,0,0,0,0,1,0,0,0,0
Stone Giant,126,139.2,13.2,4.0,2.0,-8.0,2.0,0,0,1,0,0,0,0,0,0,0,0,0,1
Guardian Naga,127,142.1,15.1,7.0,-1.0,-11.5,-1.0,1,1,0,0,1,0,0,0,0,1,0,1,0

================================================================================
cr2 | actual_hp=22 | 6 creatures | pred range: 46.3 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_disadvantage_condition,resistance_count,immunity_count,f_breath_weapon,f_incorporeal_movement,f_innate_spellcasting,f_invisibility,f_keen_senses,f_life_drain,f_magic_resistance,f_pack_tactics,f_sunlight_sensitivity
Name,,,,,,,,,,,,,,,,,,,
Dryad,22,6.6,-15.4,7.0,1.0,-3.5,2.0,0,0,0,0,0,1,0,0,0,1,0,0
Copper Dragon Wyrmling,22,32.5,10.5,8.0,-1.0,5.0,-1.0,0,0,1,1,0,0,0,0,0,0,0,0
Giant Vulture,22,43.5,21.5,-2.0,0.0,4.0,0.0,0,0,0,0,0,0,0,1,0,0,1,0
Will-o'-Wisp,22,47.2,25.2,9.0,-1.0,-8.0,-3.0,0,7,2,0,1,0,1,0,0,0,0,0
Ghoul,22,48.1,26.1,0.0,-1.0,-3.0,-2.0,0,0,1,0,0,0,0,0,0,0,0,0
Specter,22,52.9,30.9,2.0,-1.0,-1.5,-2.0,1,7,2,0,1,0,0,0,1,0,0,1

================================================================================
cr3 | actual_hp=110-112 | 6 creatures | pred range: 39.8 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,inflicts_prone,resistance_count,immunity_count,f_breath_weapon,f_brute,f_etherealness,f_innate_spellcasting,f_invisibility,f_magic_resistance,f_magic_weapons,f_nightmare_haunting,f_regeneration,f_shapechange
Name,,,,,,,,,,,,,,,,,,,,
Gladiator,112,94.7,-17.3,3.0,0.0,-9.0,0.0,1,0,0,0,1,0,0,0,0,0,0,0,0
Oni,110,98.6,-11.4,5.0,0.0,21.0,-2.0,0,0,0,0,0,0,1,1,0,1,0,1,1
Barbed Devil,110,102.8,-7.2,4.0,-1.0,-12.0,0.0,0,3,2,0,0,0,0,0,1,0,0,0,0
Young Brass Dragon,110,104.8,-5.2,6.0,0.0,11.7,-1.0,0,0,1,1,0,0,0,0,0,0,0,0,0
Night Hag,112,109.0,-3.0,4.0,0.0,-15.7,-1.0,0,4,0,0,0,1,1,0,1,0,1,0,1
Wyvern,110,134.5,24.5,-2.0,0.0,5.5,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0

================================================================================
cr2 | actual_hp=52 | 10 creatures | pred range: 38.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_advantage_condition,inflicts_prone,resistance_count,...,f_hold_breath,f_keen_senses,f_leadership,f_magic_resistance,f_pounce,f_read_thoughts,f_shapechange,f_steadfast,f_surprise_attack,f_terrain_camouflage
Name,,,,,,,,,,,,,,,,,,,,,
Giant Octopus,52,35.6,-16.4,-1.0,0.0,-2.0,4.0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
Sea Hag,52,41.1,-10.9,1.0,0.0,-7.0,3.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Saber-Toothed Tiger,52,50.4,-1.6,-1.0,1.0,-1.5,1.0,0,1,0,...,0,1,0,0,1,0,0,0,0,0
Gargoyle,52,50.8,-1.2,2.0,-1.0,-6.0,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Basilisk,52,52.0,-0.0,2.0,0.0,-6.0,-1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Knight,52,59.8,7.8,5.0,0.0,-3.0,0.0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Bearded Devil,52,62.2,10.2,4.0,0.0,-8.0,-1.0,0,0,3,...,0,0,0,1,0,0,0,1,0,0
Blue Dragon Wyrmling,52,63.3,11.3,8.0,0.0,-0.3,-1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Giant Scorpion,52,74.1,22.1,2.0,-1.0,8.5,-1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doppelganger,52,74.2,22.2,1.0,2.0,-4.7,0.0,0,0,0,...,0,0,0,0,0,1,1,0,1,0

================================================================================
cr2 | actual_hp=33 | 5 creatures | pred range: 31.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,immunity_count,f_amphibious,f_antimagic_susceptibility,f_breath_weapon,f_damage_transfer,f_false_appearance,f_keen_senses,f_shapechange,f_spellcasting
Name,,,,,,,,,,,,,,,,
Cult Fanatic,33,29.1,-3.9,2.0,-1.0,-0.5,-2.0,0,0,0,0,0,0,0,0,1
Animated Armor,33,30.0,-3.0,6.0,-1.0,-1.0,0.0,2,0,1,0,0,1,0,0,0
Rug of Smothering,33,39.5,6.5,-1.0,0.0,-17.0,0.0,2,0,1,0,1,1,0,0,0
Black Dragon Wyrmling,33,42.7,9.7,8.0,-1.0,4.3,-2.0,1,1,0,1,0,0,0,0,0
Wererat,33,60.8,27.8,-1.0,-1.0,-11.5,-2.0,3,0,0,0,0,0,1,1,0

================================================================================
cr2 | actual_hp=27 | 5 creatures | pred range: 28.0 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_advantage_condition,resistance_count,f_brute,f_sneak_attack,f_spellcasting,f_surprise_attack,f_terrain_camouflage
Name,,,,,,,,,,,,,,
Spy,27,35.7,8.7,0.0,-1.0,6.0,0.0,1,0,0,1,0,0,0
Bugbear,27,41.2,14.2,4.0,-1.0,1.3,0.0,0,0,1,0,0,1,0
Grick,27,49.9,22.9,1.0,-1.0,-2.5,0.0,0,3,0,0,0,0,1
Druid,27,56.4,29.4,4.0,-1.0,-4.4,-1.0,0,0,0,0,1,0,0
Priest,27,63.8,36.8,0.0,-3.0,-3.0,0.0,1,0,0,0,1,0,0

================================================================================
cr1 | actual_hp=13 | 11 creatures | pred range: 24.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_advantage_condition,has_disadvantage_condition,inflicts_prone,...,immunity_count,f_amphibious,f_charge,f_constrict,f_false_appearance,f_fey_ancestry,f_innate_spellcasting,f_keen_senses,f_pounce,f_sunlight_sensitivity
Name,,,,,,,,,,,,,,,,,,,,,
Drow,13,-0.0,-13.0,4.0,1.0,0.5,2.0,1,1,0,...,0,0,0,0,0,1,1,0,0,1
Constrictor Snake,13,3.5,-9.5,2.0,1.0,1.5,3.0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
Giant Crab,13,6.4,-6.6,4.0,0.0,1.5,0.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Lemure,13,6.6,-6.4,-3.0,1.0,0.5,0.0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
Elk,13,7.7,-5.3,-1.0,2.0,3.0,2.0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
Skeleton,13,9.4,-3.6,2.0,1.0,0.5,0.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Panther,13,10.0,-3.0,1.0,1.0,2.3,1.0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
Riding Horse,13,15.4,2.4,-1.0,2.0,3.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Giant Badger,13,16.9,3.9,-1.0,0.0,5.5,0.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Shrieker,13,17.5,4.5,-5.0,-2.0,-2.0,0.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Giant Wasp,13,24.6,11.6,0.0,0.0,8.0,-1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

================================================================================
cr1 | actual_hp=11 | 12 creatures | pred range: 22.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,inflicts_prone,immunity_count,f_amphibious,f_blind_senses,f_charge,f_keen_senses,f_martial_advantage,f_pack_tactics,f_relentless,f_spider_climb,f_sure_footed,f_terrain_camouflage,f_web_sense,f_web_walker
Name,,,,,,,,,,,,,,,,,,,,
Giant Poisonous Snake,11,0.0,-11.0,3.0,3.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Guard,11,4.1,-6.9,5.0,0.0,2.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Giant Wolf Spider,11,5.7,-5.3,2.0,0.0,6.5,0,0,0,0,0,0,0,0,0,1,0,0,1,1
Tribal Warrior,11,8.9,-2.1,1.0,1.0,1.5,0,0,0,0,0,0,0,1,0,0,0,0,0,0
Pony,11,10.0,-1.0,-1.0,1.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bandit,11,10.1,-0.9,1.0,0.0,2.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Wolf,11,10.2,-0.8,2.0,2.0,2.0,1,0,0,0,0,1,0,1,0,0,0,0,0,0
Grimlock,11,13.2,2.2,0.0,2.0,3.0,0,1,0,1,0,1,0,0,0,0,0,1,0,0
Mule,11,15.1,4.1,-1.0,-1.0,1.5,1,0,0,0,0,0,0,0,0,0,1,0,0,0
Merfolk,11,15.1,4.1,0.0,-1.0,0.5,0,0,1,0,0,0,0,0,0,0,0,0,0,0
Boar,11,19.1,8.1,0.0,0.0,-0.5,1,0,0,0,1,0,0,0,1,0,0,0,0,0
Hobgoblin,11,22.6,11.6,6.0,-1.0,4.5,0,0,0,0,0,0,1,0,0,0,0,0,0,0

================================================================================
cr1 | actual_hp=19 | 9 creatures | pred range: 21.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,inflicts_prone,f_charge,f_flyby,f_hold_breath,f_keen_senses,f_sure_footed
Name,,,,,,,,,,,,,
Draft Horse,19,12.7,-6.3,-1.0,3.0,4.0,0.0,0,0,0,0,0,0
Giant Lizard,19,15.5,-3.5,1.0,1.0,1.5,0.0,0,0,0,0,0,0
Giant Owl,19,16.4,-2.6,1.0,0.0,3.0,0.0,0,0,1,0,1,0
Axe Beak,19,17.0,-2.0,0.0,1.0,1.5,0.0,0,0,0,0,0,0
Warhorse,19,18.4,-0.6,-1.0,2.0,6.7,2.0,1,1,0,0,0,0
Ape,19,27.2,8.2,0.0,1.0,5.0,0.0,0,0,0,0,0,0
Giant Goat,19,28.9,9.9,-1.0,1.0,0.0,1.0,1,1,0,0,0,1
Black Bear,19,33.1,14.1,-1.0,-1.0,4.5,0.0,0,0,0,0,1,0
Crocodile,19,34.0,15.0,0.0,0.0,-0.5,0.0,0,0,0,1,0,0

================================================================================
cr1 | actual_hp=22 | 17 creatures | pred range: 20.1 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,has_advantage_condition,has_disadvantage_condition,resistance_count,...,f_hold_breath,f_innate_spellcasting,f_keen_senses,f_pack_tactics,f_rampage,f_relentless,f_spider_climb,f_teleport,f_web_sense,f_web_walker
Name,,,,,,,,,,,,,,,,,,,,,
Swarm of Bats,22,12.0,-10.0,1.0,1.0,0.0,0.0,0,0,3,...,0,0,1,0,0,0,0,0,0,0
Giant Bat,22,14.8,-7.2,2.0,1.0,0.5,0.0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Blink Dog,22,16.9,-5.1,2.0,0.0,-0.5,0.0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
Swarm of Centipedes,22,19.2,-2.8,0.0,-1.0,2.0,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Warhorse Skeleton,22,21.2,-0.8,1.0,2.0,3.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Darkmantle,22,22.3,0.3,-1.0,1.0,-1.5,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Magma Mephit,22,23.0,1.0,1.0,-1.0,6.0,-1.0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
Zombie,22,24.4,2.4,-3.0,0.0,-0.5,0.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Swarm of Insects,22,25.1,3.1,0.0,-1.0,2.0,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Swarm of Spiders,22,25.1,3.1,0.0,-1.0,2.0,0.0,0,0,3,...,0,0,0,0,0,0,1,0,1,1
Swarm of Beetles,22,25.1,3.1,0.0,-1.0,2.0,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Swarm of Wasps,22,25.1,3.1,0.0,-1.0,2.0,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Lizardfolk,22,26.2,4.2,3.0,0.0,3.0,0.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Sahuagin,22,27.8,5.8,0.0,3.0,-1.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gray Ooze,22,28.8,6.8,-4.0,-1.0,3.5,0.0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
Gnoll,22,28.9,6.9,3.0,0.0,-0.5,0.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Reef Shark,22,32.1,10.1,0.0,1.0,-1.5,0.0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

================================================================================
cr2 | actual_hp=59 | 5 creatures | pred range: 19.5 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,resistance_count,f_false_appearance,f_keen_senses
Name,,,,,,,,,
Griffon,59,52.6,-6.4,-1.0,1.0,2.5,0,0,1
Pegasus,59,56.1,-2.9,1.0,1.0,-6.0,0,0,0
Ogre,59,61.6,2.6,-2.0,1.0,-4.0,0,0,0
Awakened Tree,59,62.2,3.2,0.0,1.0,-2.5,2,1,0
Owlbear,59,72.1,13.1,0.0,2.0,1.5,0,0,1

================================================================================
cr1 | actual_hp=9 | 5 creatures | pred range: 15.8 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,resistance_count,immunity_count,f_death_burst,f_keen_senses,f_spellcasting
Name,,,,,,,,,,,,
Giant Weasel,9,4.6,-4.4,2.0,2.0,2.5,0.0,0,0,0,1,0
Noble,9,5.6,-3.4,4.0,0.0,2.5,0.0,0,0,0,0,0
Cultist,9,9.0,0.0,1.0,0.0,1.5,0.0,0,0,0,0,0
Acolyte,9,15.2,6.2,-1.0,-0.5,-0.5,1.0,0,0,0,0,1
Magmin,9,20.4,11.4,2.0,0.0,7.2,-1.0,3,1,1,0,0

================================================================================
cr1 | actual_hp=1 | 11 creatures | pred range: 12.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,f_amphibious,f_blood_frenzy,f_echolocation,f_flyby,f_keen_senses,f_mimicry,f_spider_climb,f_standing_leap,f_web_sense,f_web_walker
Name,,,,,,,,,,,,,,,,,
Quipper,1,-4.6,-5.6,3.0,7.0,-1.0,0.0,0,1,0,0,0,0,0,0,0,0
Hawk,1,-2.6,-3.6,3.0,3.0,-1.0,0.0,0,0,0,0,1,0,0,0,0,0
Weasel,1,-2.6,-3.6,3.0,3.0,-1.0,0.0,0,0,0,0,1,0,0,0,0,0
Raven,1,-1.8,-2.8,2.0,2.0,-1.0,0.0,0,0,0,0,0,1,0,0,0,0
Spider,1,-1.4,-2.4,2.0,2.0,1.5,-1.0,0,0,0,0,0,0,1,0,1,1
Owl,1,0.4,-0.6,1.0,1.0,-1.0,0.0,0,0,0,1,1,0,0,0,0,0
Scorpion,1,2.5,1.5,1.0,0.0,3.5,-1.0,0,0,0,0,0,0,0,0,0,0
Bat,1,4.9,3.9,2.0,-2.0,-1.0,0.0,0,0,1,0,1,0,0,0,0,0
Sea Horse,1,7.2,6.2,1.0,-2.0,-2.0,0.0,0,0,0,0,0,0,0,0,0,0
Frog,1,7.2,6.2,1.0,-2.0,-2.0,0.0,1,0,0,0,0,0,0,1,0,0
Rat,1,7.9,6.9,0.0,-2.0,-1.0,0.0,0,0,0,0,1,0,0,0,0,0

================================================================================
cr1 | actual_hp=5 | 6 creatures | pred range: 12.3 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,has_disadvantage_condition,inflicts_prone,immunity_count,f_flyby,f_keen_senses,f_pack_tactics,f_sunlight_sensitivity
Name,,,,,,,,,,,,,
Homunculus,5,-2.1,-7.1,3.0,2.0,-1.0,0,0,1,0,0,0,0
Flying Snake,5,-1.6,-6.6,3.0,3.0,5.5,0,0,0,1,0,0,0
Hyena,5,-0.0,-5.0,1.0,1.0,1.5,0,0,0,0,0,1,0
Vulture,5,2.1,-2.9,0.0,1.0,0.5,0,0,0,0,1,1,0
Kobold,5,7.2,2.2,1.0,2.0,1.5,1,0,0,0,0,1,1
Mastiff,5,10.1,5.1,1.0,0.0,1.5,0,1,0,0,1,0,0

================================================================================
cr1 | actual_hp=7 | 5 creatures | pred range: 11.9 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,f_keen_senses,f_magic_resistance,f_nimble_escape,f_pack_tactics
Name,,,,,,,,,,,
Goblin,7,-1.4,-8.4,8.0,5.0,0.5,0.0,0,0,1,0
Giant Rat,7,6.2,-0.8,1.0,2.0,1.5,0.0,1,0,0,1
Blood Hawk,7,6.2,-0.8,1.0,2.0,1.5,0.0,1,0,0,1
Diseased Giant Rat,7,9.7,2.7,1.0,2.0,1.5,-1.0,1,0,0,1
Pseudodragon,7,10.5,3.5,4.0,1.0,-0.5,0.0,1,1,0,0

================================================================================
cr1 | actual_hp=2 | 6 creatures | pred range: 6.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,save_dc_deviation,f_amphibious,f_invisibility,f_keen_senses
Name,,,,,,,,,,
Stirge,2,1.8,-0.2,3.0,2.0,2.5,0.0,0,0,0
Cat,2,4.9,2.9,2.0,-2.0,-1.0,0.0,0,0,1
Poisonous Snake,2,6.4,4.4,2.0,2.0,3.0,-1.0,0,0,0
Crab,2,6.4,4.4,1.0,-2.0,-1.0,0.0,1,0,0
Lizard,2,7.9,5.9,0.0,-2.0,-1.0,0.0,0,0,0
Sprite,2,8.2,6.2,7.0,3.0,-4.0,-1.0,0,1,0

================================================================================
cr1 | actual_hp=3 | 5 creatures | pred range: 5.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,f_hold_breath,f_keen_senses,f_pack_tactics,f_terrain_camouflage
Name,,,,,,,,,,
Eagle,3,-1.8,-4.8,2.0,2.0,2.5,0,1,0,0
Octopus,3,-1.1,-4.1,2.0,2.0,-1.0,1,0,0,1
Baboon,3,-0.3,-3.3,2.0,0.0,1.5,0,0,1,0
Jackal,3,-0.3,-3.3,2.0,0.0,1.5,0,1,1,0
Badger,3,3.9,0.9,0.0,0.0,-1.0,0,1,0,0

================================================================================
cr1 | actual_hp=4 | 5 creatures | pred range: 4.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation,attack_deviation,dpr_deviation,inflicts_prone,f_charge,f_illumination,f_sure_footed
Name,,,,,,,,,,
Giant Fire Beetle,4,-0.5,-4.5,3.0,-1.0,2.5,0,0,1,0
Deer,4,-0.1,-4.1,3.0,0.0,0.5,0,0,0,0
Giant Centipede,4,0.4,-3.6,2.0,1.0,10.0,0,0,0,0
Goat,4,0.6,-3.4,0.0,1.0,1.5,1,1,0,1
Commoner,4,4.1,0.1,0.0,0.0,0.5,0,0,0,0

In [6]:
import sys
sys.path.insert(0, '../..')
from notebooks.helper_files.feature_config import (
    PHASE2_PENALTIES, DMG_AC_ADJUSTMENTS, DMG_ATTACK_ADJUSTMENTS,
    DMG_DPR_ADJUSTMENTS, DMG_HP_PER_USE, DMG_HP_BY_TIER,
    DMG_HP_PERCENTAGE, DMG_HP_MULTIPLIER,
    RESISTANCE_PENALTY_PER_COUNT, IMMUNITY_PENALTY_PER_COUNT,
)

def feature_hp_cost(feat_name, tier):
    """Compute the HP cost of a single DMG feature for a given tier."""
    penalties = PHASE2_PENALTIES[tier]
    cost = 0.0
    ac_key = feat_name.replace('_', ' ')
    if ac_key in DMG_AC_ADJUSTMENTS:
        cost += DMG_AC_ADJUSTMENTS[ac_key] * penalties['ac_deviation']
    if ac_key in DMG_ATTACK_ADJUSTMENTS:
        cost += DMG_ATTACK_ADJUSTMENTS[ac_key] * penalties['attack_deviation']
    if feat_name in DMG_DPR_ADJUSTMENTS:
        cost += DMG_DPR_ADJUSTMENTS[feat_name] * penalties['dpr_deviation']
    if feat_name in DMG_HP_PER_USE:
        cost -= DMG_HP_PER_USE[feat_name].get(tier, 0) * 3
    if feat_name in DMG_HP_BY_TIER:
        cost -= DMG_HP_BY_TIER[feat_name].get(tier, 0)
    if feat_name in DMG_HP_PERCENTAGE:
        tier_df = df[df['cr_tier'] == tier]
        mean_baseline = tier_df['hp_baseline'].mean()
        pct = DMG_HP_PERCENTAGE[feat_name]
        cost -= mean_baseline * pct / (1 + pct)
    if feat_name in DMG_HP_MULTIPLIER:
        tier_df = df[df['cr_tier'] == tier]
        mean_baseline = tier_df['hp_baseline'].mean()
        mult = DMG_HP_MULTIPLIER[feat_name]
        cost -= mean_baseline * (1 - 1 / mult)
    return cost

def build_group_cost_df(names):
    """Show HP impact of each feature value. Every cell = value × penalty rate."""
    group = df[df['Name'].isin(names)].sort_values('predicted_hp')
    tier = group['cr_tier'].iloc[0]
    penalties = PHASE2_PENALTIES[tier]

    core = ['Name', 'actual_hp', 'predicted_hp', 'hp_delta']
    result = group[core].copy()

    # Phase 2 columns → value × penalty rate
    for col in phase2_cols:
        if col in group.columns and group[col].nunique() > 1:
            rate = penalties.get(col, 0)
            col_name = f'{col} [×{rate:+.2f}]'
            result[col_name] = (group[col].values * rate).round(1)

    # Resistance/immunity → actual HP penalty per creature
    resist_penalty = (group['hp_after_phase2'] - group['hp_after_resist_immun_penalty']).values
    resist_varies = len(set(resist_penalty.round(1))) > 1
    if resist_varies:
        result['resist+immun penalty'] = (-resist_penalty).round(1)

    # Feature flags → 0/1 × feature HP cost
    for col in feature_flag_cols:
        if col in group.columns and group[col].nunique() > 1:
            feat_name = col.replace('feature_', '')
            cost = feature_hp_cost(feat_name, tier)
            cost_label = f'{cost:+.1f}' if cost != 0 else 'no cost'
            col_name = f'f_{feat_name} [{cost_label}]'
            result[col_name] = (group[col].values * cost).round(1) if cost != 0 else group[col].values

    result = result.set_index('Name')
    return result.round(1)

print('Ready')

Ready

In [7]:
# Same groups, but feature columns show HP cost instead of 0/1 flags.
# Column headers include the per-creature cost in brackets.
for _, row in groups.iterrows():
    tier, hp_label, count = row['cr_tier'], row['hp_label'], int(row['count'])
    print(f'\n{"="*80}')
    print(f'{tier} | actual_hp={hp_label} | {count} creatures | pred range: {row["pred_range"]:.1f} HP')
    print(f'{"="*80}')
    display(build_group_cost_df(row['names']))

================================================================================
cr3 | actual_hp=136-138 | 7 creatures | pred range: 68.2 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-3.50],attack_deviation [×-4.00],dpr_deviation [×-1.25],save_dc_deviation [×-6.00],resist+immun penalty,f_amphibious [no cost],f_angelic_weapons [no cost],f_breath_weapon [no cost],f_damage_absorption [no cost],f_false_appearance [no cost],f_innate_spellcasting [no cost],f_magic_resistance [-7.0],f_shapechange [no cost],f_siege_monster [no cost],f_stench [-3.5]
Name,,,,,,,,,,,,,,,,,,
Shambling Mound,136,118.9,-17.1,-0.0,-0.0,11.2,6.0,-0.0,0,0,0,1,0,0,-0.0,0,0,-0.0
Hezrou,136,136.7,0.7,-21.0,-0.0,20.0,6.0,-10.5,0,0,0,0,0,0,-7.0,0,0,-3.5
Young Green Dragon,136,139.3,3.3,-24.5,-0.0,-5.4,6.0,-0.0,1,0,1,0,0,0,-0.0,0,0,-0.0
Tyrannosaurus Rex,136,149.4,13.4,7.0,-12.0,-0.6,-12.0,-0.0,0,0,0,0,0,0,-0.0,0,0,-0.0
Frost Giant,138,159.4,21.4,-7.0,-8.0,2.5,-0.0,-0.0,0,0,0,0,0,0,-0.0,0,0,-0.0
Deva,136,172.7,36.7,-14.0,4.0,17.5,-0.0,-12.1,0,1,0,0,0,1,-7.0,1,0,-0.0
Treant,138,187.1,49.1,-0.0,-8.0,32.5,-0.0,-0.0,0,0,0,0,1,0,-0.0,0,1,-0.0

================================================================================
cr2 | actual_hp=45 | 10 creatures | pred range: 64.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],save_dc_deviation [×-5.00],has_disadvantage_condition [×+1.50],inflicts_prone [×-1.12],resist+immun penalty,...,f_etherealness [no cost],f_horrifying_visage [-12.8],f_incorporeal_movement [no cost],f_keen_senses [no cost],f_life_drain [no cost],f_pack_tactics [-3.0],f_possession [-31.9],f_rampage [-2.0],f_spider_climb [no cost],f_sunlight_sensitivity [no cost]
Name,,,,,,,,,,,,,,,,,,,,,
Ghost,45,10.9,-34.1,7.5,3.0,11.0,5.0,0.0,-0.0,-21.3,...,1,-12.8,1,0,0,-0.0,-31.9,-0.0,0,0
Silver Dragon Wyrmling,45,12.3,-32.7,-20.0,-3.0,-1.3,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,0,0
Centaur,45,38.6,-6.4,2.5,-3.0,-16.5,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,0,0
Rhinoceros,45,46.4,1.4,5.0,-6.0,3.0,-10.0,0.0,-1.1,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,0,0
Hunter Shark,45,47.1,2.1,2.5,-15.0,4.0,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,0,0
Giant Hyena,45,51.1,6.1,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-2.0,0,0
Merrow,45,52.1,7.1,-0.0,-3.0,-0.5,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,0,0
Hell Hound,45,65.8,20.8,-5.0,-3.0,-0.7,5.0,0.0,-0.0,-0.0,...,0,-0.0,0,1,0,-3.0,-0.0,-0.0,0,0
Wight,45,67.4,22.4,-2.5,3.0,-3.0,-0.0,1.5,-0.0,-9.6,...,0,-0.0,0,0,1,-0.0,-0.0,-0.0,0,1
Ochre Jelly,45,75.6,30.6,12.5,3.0,4.5,-0.0,0.0,-0.0,-0.0,...,0,-0.0,0,0,0,-0.0,-0.0,-0.0,1,0

================================================================================
cr3 | actual_hp=126-127 | 7 creatures | pred range: 57.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-3.50],attack_deviation [×-4.00],dpr_deviation [×-1.25],save_dc_deviation [×-6.00],has_advantage_condition [×-3.00],has_disadvantage_condition [×+2.00],inflicts_prone [×-1.50],resist+immun penalty,f_amphibious [no cost],f_blood_frenzy [-16.0],f_breath_weapon [no cost],f_charge [no cost],f_rejuvenation [no cost],f_siege_monster [no cost],f_spellcasting [no cost],f_terrain_camouflage [no cost]
Name,,,,,,,,,,,,,,,,,,,
Earth Elemental,126,84.7,-41.3,-7.0,-4.0,8.8,-0.0,-0.0,0.0,-0.0,-7.0,0,-0.0,0,0,0,1,0,0
Medusa,127,115.1,-11.9,-0.0,8.0,14.4,6.0,-0.0,0.0,-0.0,-0.0,0,-0.0,0,0,0,0,0,0
Young Black Dragon,127,120.8,-6.2,-24.5,-0.0,-16.7,6.0,-0.0,0.0,-0.0,-0.0,1,-0.0,1,0,0,0,0,0
Giant Shark,126,121.4,-4.6,7.0,-24.0,15.6,-0.0,-0.0,0.0,-0.0,-0.0,0,-16.0,0,0,0,0,0,0
Mammoth,126,121.5,-4.5,7.0,-12.0,2.9,-18.0,-0.0,0.0,-1.5,-0.0,0,-0.0,0,1,0,0,0,0
Stone Giant,126,139.2,13.2,-14.0,-8.0,10.0,-12.0,-0.0,0.0,-1.5,-0.0,0,-0.0,0,0,0,0,0,1
Guardian Naga,127,142.1,15.1,-24.5,4.0,14.4,6.0,-3.0,2.0,-0.0,-0.0,0,-0.0,0,0,1,0,1,0

================================================================================
cr2 | actual_hp=22 | 6 creatures | pred range: 46.3 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],save_dc_deviation [×-5.00],has_disadvantage_condition [×+1.50],resist+immun penalty,f_breath_weapon [no cost],f_incorporeal_movement [no cost],f_innate_spellcasting [no cost],f_invisibility [-2.5],f_keen_senses [no cost],f_life_drain [no cost],f_magic_resistance [-5.0],f_pack_tactics [-3.0],f_sunlight_sensitivity [no cost]
Name,,,,,,,,,,,,,,,,,,
Dryad,22,6.6,-15.4,-17.5,-3.0,3.5,-10.0,0.0,-0.0,0,0,1,-0.0,0,0,-5.0,-0.0,0
Copper Dragon Wyrmling,22,32.5,10.5,-20.0,3.0,-5.0,5.0,0.0,-0.0,1,0,0,-0.0,0,0,-0.0,-0.0,0
Giant Vulture,22,43.5,21.5,5.0,-0.0,-4.0,-0.0,0.0,-0.0,0,0,0,-0.0,1,0,-0.0,-3.0,0
Will-o'-Wisp,22,47.2,25.2,-22.5,3.0,8.0,15.0,0.0,-7.2,0,1,0,-2.5,0,0,-0.0,-0.0,0
Ghoul,22,48.1,26.1,-0.0,3.0,3.0,10.0,0.0,-0.0,0,0,0,-0.0,0,0,-0.0,-0.0,0
Specter,22,52.9,30.9,-5.0,3.0,1.5,10.0,1.5,-7.6,0,1,0,-0.0,0,1,-0.0,-0.0,1

================================================================================
cr3 | actual_hp=110-112 | 6 creatures | pred range: 39.8 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-3.50],attack_deviation [×-4.00],dpr_deviation [×-1.25],save_dc_deviation [×-6.00],inflicts_prone [×-1.50],resist+immun penalty,f_breath_weapon [no cost],f_brute [no cost],f_etherealness [no cost],f_innate_spellcasting [no cost],f_invisibility [-3.5],f_magic_resistance [-7.0],f_magic_weapons [no cost],f_nightmare_haunting [no cost],f_regeneration [no cost],f_shapechange [no cost]
Name,,,,,,,,,,,,,,,,,,,
Gladiator,112,94.7,-17.3,-10.5,-0.0,11.2,-0.0,-1.5,-0.0,0,1,0,0,-0.0,-0.0,0,0,0,0
Oni,110,98.6,-11.4,-17.5,-0.0,-26.2,12.0,-0.0,-0.0,0,0,0,1,-3.5,-0.0,1,0,1,1
Barbed Devil,110,102.8,-7.2,-14.0,4.0,15.0,-0.0,-0.0,-7.4,0,0,0,0,-0.0,-7.0,0,0,0,0
Young Brass Dragon,110,104.8,-5.2,-21.0,-0.0,-14.6,6.0,-0.0,-0.0,1,0,0,0,-0.0,-0.0,0,0,0,0
Night Hag,112,109.0,-3.0,-14.0,-0.0,19.6,6.0,-0.0,-7.8,0,0,1,1,-0.0,-7.0,0,1,0,1
Wyvern,110,134.5,24.5,7.0,-0.0,-6.9,-0.0,-0.0,-0.0,0,0,0,0,-0.0,-0.0,0,0,0,0

================================================================================
cr2 | actual_hp=52 | 10 creatures | pred range: 38.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],save_dc_deviation [×-5.00],has_advantage_condition [×-2.25],inflicts_prone [×-1.12],resist+immun penalty,...,f_hold_breath [no cost],f_keen_senses [no cost],f_leadership [no cost],f_magic_resistance [-5.0],f_pounce [no cost],f_read_thoughts [no cost],f_shapechange [no cost],f_steadfast [no cost],f_surprise_attack [no cost],f_terrain_camouflage [no cost]
Name,,,,,,,,,,,,,,,,,,,,,
Giant Octopus,52,35.6,-16.4,2.5,-0.0,2.0,-20.0,-0.0,-0.0,-0.0,...,1,0,0,-0.0,0,0,0,0,0,1
Sea Hag,52,41.1,-10.9,-2.5,-0.0,7.0,-15.0,-2.2,-0.0,-0.0,...,0,0,0,-0.0,0,0,0,0,0,0
Saber-Toothed Tiger,52,50.4,-1.6,2.5,-3.0,1.5,-5.0,-0.0,-1.1,-0.0,...,0,1,0,-0.0,1,0,0,0,0,0
Gargoyle,52,50.8,-1.2,-5.0,3.0,6.0,-0.0,-0.0,-0.0,-7.2,...,0,0,0,-0.0,0,0,0,0,0,0
Basilisk,52,52.0,-0.0,-5.0,-0.0,6.0,5.0,-0.0,-0.0,-0.0,...,0,0,0,-0.0,0,0,0,0,0,0
Knight,52,59.8,7.8,-12.5,-0.0,3.0,-0.0,-0.0,-0.0,-0.0,...,0,0,1,-0.0,0,0,0,0,0,0
Bearded Devil,52,62.2,10.2,-10.0,-0.0,8.0,5.0,-0.0,-0.0,-10.1,...,0,0,0,-5.0,0,0,0,1,0,0
Blue Dragon Wyrmling,52,63.3,11.3,-20.0,-0.0,0.3,5.0,-0.0,-0.0,-0.0,...,0,0,0,-0.0,0,0,0,0,0,0
Giant Scorpion,52,74.1,22.1,-5.0,3.0,-8.5,5.0,-0.0,-0.0,-0.0,...,0,0,0,-0.0,0,0,0,0,0,0
Doppelganger,52,74.2,22.2,-2.5,-6.0,4.7,-0.0,-0.0,-0.0,-0.0,...,0,0,0,-0.0,0,1,1,0,1,0

================================================================================
cr2 | actual_hp=33 | 5 creatures | pred range: 31.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],save_dc_deviation [×-5.00],resist+immun penalty,f_amphibious [no cost],f_antimagic_susceptibility [no cost],f_breath_weapon [no cost],f_damage_transfer [-31.9],f_false_appearance [no cost],f_keen_senses [no cost],f_shapechange [no cost],f_spellcasting [no cost]
Name,,,,,,,,,,,,,,,,
Cult Fanatic,33,29.1,-3.9,-5.0,3.0,0.5,10.0,-0.0,0,0,0,-0.0,0,0,0,1
Animated Armor,33,30.0,-3.0,-15.0,3.0,1.0,-0.0,-0.0,0,1,0,-0.0,1,0,0,0
Rug of Smothering,33,39.5,6.5,2.5,-0.0,17.0,-0.0,-0.0,0,1,0,-31.9,1,0,0,0
Black Dragon Wyrmling,33,42.7,9.7,-20.0,3.0,-4.3,10.0,-0.0,1,0,1,-0.0,0,0,0,0
Wererat,33,60.8,27.8,2.5,3.0,11.5,10.0,-20.2,0,0,0,-0.0,0,1,1,0

================================================================================
cr2 | actual_hp=27 | 5 creatures | pred range: 28.0 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],save_dc_deviation [×-5.00],has_advantage_condition [×-2.25],resist+immun penalty,f_brute [no cost],f_sneak_attack [no cost],f_spellcasting [no cost],f_surprise_attack [no cost],f_terrain_camouflage [no cost]
Name,,,,,,,,,,,,,,
Spy,27,35.7,8.7,-0.0,3.0,-6.0,-0.0,-2.2,-0.0,0,1,0,0,0
Bugbear,27,41.2,14.2,-10.0,3.0,-1.3,-0.0,-0.0,-0.0,1,0,0,1,0
Grick,27,49.9,22.9,-2.5,3.0,2.5,-0.0,-0.0,-7.1,0,0,0,0,1
Druid,27,56.4,29.4,-10.0,3.0,4.4,5.0,-0.0,-0.0,0,0,1,0,0
Priest,27,63.8,36.8,-0.0,9.0,3.0,-0.0,-2.2,-0.0,0,0,1,0,0

================================================================================
cr1 | actual_hp=13 | 11 creatures | pred range: 24.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],has_advantage_condition [×-1.50],has_disadvantage_condition [×+1.00],inflicts_prone [×-0.75],f_amphibious [no cost],f_charge [no cost],f_constrict [-1.5],f_false_appearance [no cost],f_fey_ancestry [no cost],f_innate_spellcasting [no cost],f_keen_senses [no cost],f_pounce [no cost],f_sunlight_sensitivity [no cost]
Name,,,,,,,,,,,,,,,,,,,
Drow,13,-0.0,-13.0,-6.0,-2.0,-0.4,-7.0,-1.5,1.0,-0.0,0,0,-0.0,0,1,1,0,0,1
Constrictor Snake,13,3.5,-9.5,-3.0,-2.0,-1.1,-10.5,-0.0,0.0,-0.0,0,0,-1.5,0,0,0,0,0,0
Giant Crab,13,6.4,-6.6,-6.0,-0.0,-1.1,-0.0,-0.0,0.0,-0.0,1,0,-0.0,0,0,0,0,0,0
Lemure,13,6.6,-6.4,4.5,-2.0,-0.4,-0.0,-0.0,0.0,-0.0,0,0,-0.0,0,0,0,0,0,0
Elk,13,7.7,-5.3,1.5,-4.0,-2.2,-7.0,-0.0,0.0,-0.8,0,1,-0.0,0,0,0,0,0,0
Skeleton,13,9.4,-3.6,-3.0,-2.0,-0.4,-0.0,-0.0,0.0,-0.0,0,0,-0.0,0,0,0,0,0,0
Panther,13,10.0,-3.0,-1.5,-2.0,-1.7,-3.5,-0.0,0.0,-0.8,0,0,-0.0,0,0,0,1,1,0
Riding Horse,13,15.4,2.4,1.5,-4.0,-2.2,-0.0,-0.0,0.0,-0.0,0,0,-0.0,0,0,0,0,0,0
Giant Badger,13,16.9,3.9,1.5,-0.0,-4.1,-0.0,-0.0,0.0,-0.0,0,0,-0.0,0,0,0,1,0,0
Shrieker,13,17.5,4.5,7.5,4.0,1.5,-0.0,-0.0,0.0,-0.0,0,0,-0.0,1,0,0,0,0,0
Giant Wasp,13,24.6,11.6,-0.0,-0.0,-6.0,3.5,-0.0,0.0,-0.0,0,0,-0.0,0,0,0,0,0,0

================================================================================
cr1 | actual_hp=11 | 12 creatures | pred range: 22.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],inflicts_prone [×-0.75],f_amphibious [no cost],f_blind_senses [no cost],f_charge [no cost],f_keen_senses [no cost],f_martial_advantage [no cost],f_pack_tactics [-2.0],f_relentless [no cost],f_spider_climb [no cost],f_sure_footed [no cost],f_terrain_camouflage [no cost],f_web_sense [no cost],f_web_walker [no cost]
Name,,,,,,,,,,,,,,,,,,,
Giant Poisonous Snake,11,0.0,-11.0,-4.5,-6.0,-9.0,-0.0,0,0,0,0,0,-0.0,0,0,0,0,0,0
Guard,11,4.1,-6.9,-7.5,-0.0,-1.9,-0.0,0,0,0,0,0,-0.0,0,0,0,0,0,0
Giant Wolf Spider,11,5.7,-5.3,-3.0,-0.0,-4.9,-0.0,0,0,0,0,0,-0.0,0,1,0,0,1,1
Tribal Warrior,11,8.9,-2.1,-1.5,-2.0,-1.1,-0.0,0,0,0,0,0,-2.0,0,0,0,0,0,0
Pony,11,10.0,-1.0,1.5,-2.0,-3.0,-0.0,0,0,0,0,0,-0.0,0,0,0,0,0,0
Bandit,11,10.1,-0.9,-1.5,-0.0,-1.9,-0.0,0,0,0,0,0,-0.0,0,0,0,0,0,0
Wolf,11,10.2,-0.8,-3.0,-4.0,-1.5,-0.8,0,0,0,1,0,-2.0,0,0,0,0,0,0
Grimlock,11,13.2,2.2,-0.0,-4.0,-2.2,-0.0,0,1,0,1,0,-0.0,0,0,0,1,0,0
Mule,11,15.1,4.1,1.5,2.0,-1.1,-0.8,0,0,0,0,0,-0.0,0,0,1,0,0,0
Merfolk,11,15.1,4.1,-0.0,2.0,-0.4,-0.0,1,0,0,0,0,-0.0,0,0,0,0,0,0
Boar,11,19.1,8.1,-0.0,-0.0,0.4,-0.8,0,0,1,0,0,-0.0,1,0,0,0,0,0
Hobgoblin,11,22.6,11.6,-9.0,2.0,-3.4,-0.0,0,0,0,0,1,-0.0,0,0,0,0,0,0

================================================================================
cr1 | actual_hp=19 | 9 creatures | pred range: 21.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],inflicts_prone [×-0.75],f_charge [no cost],f_flyby [no cost],f_hold_breath [no cost],f_keen_senses [no cost],f_sure_footed [no cost]
Name,,,,,,,,,,,,,
Draft Horse,19,12.7,-6.3,1.5,-6.0,-3.0,-0.0,-0.0,0,0,0,0,0
Giant Lizard,19,15.5,-3.5,-1.5,-2.0,-1.1,-0.0,-0.0,0,0,0,0,0
Giant Owl,19,16.4,-2.6,-1.5,-0.0,-2.2,-0.0,-0.0,0,1,0,1,0
Axe Beak,19,17.0,-2.0,-0.0,-2.0,-1.1,-0.0,-0.0,0,0,0,0,0
Warhorse,19,18.4,-0.6,1.5,-4.0,-5.0,-7.0,-0.8,1,0,0,0,0
Ape,19,27.2,8.2,-0.0,-2.0,-3.8,-0.0,-0.0,0,0,0,0,0
Giant Goat,19,28.9,9.9,1.5,-2.0,-0.0,-3.5,-0.8,1,0,0,0,1
Black Bear,19,33.1,14.1,1.5,2.0,-3.4,-0.0,-0.0,0,0,0,1,0
Crocodile,19,34.0,15.0,-0.0,-0.0,0.4,-0.0,-0.0,0,0,1,0,0

================================================================================
cr1 | actual_hp=22 | 17 creatures | pred range: 20.1 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],has_advantage_condition [×-1.50],has_disadvantage_condition [×+1.00],resist+immun penalty,...,f_hold_breath [no cost],f_innate_spellcasting [no cost],f_keen_senses [no cost],f_pack_tactics [-2.0],f_rampage [-1.5],f_relentless [no cost],f_spider_climb [no cost],f_teleport [no cost],f_web_sense [no cost],f_web_walker [no cost]
Name,,,,,,,,,,,,,,,,,,,,,
Swarm of Bats,22,12.0,-10.0,-1.5,-2.0,-0.0,-0.0,-0.0,0.0,-4.0,...,0,0,1,-0.0,-0.0,0,0,0,0,0
Giant Bat,22,14.8,-7.2,-3.0,-2.0,-0.4,-0.0,-0.0,0.0,-0.0,...,0,0,1,-0.0,-0.0,0,0,0,0,0
Blink Dog,22,16.9,-5.1,-3.0,-0.0,0.4,-0.0,-0.0,0.0,-0.0,...,0,0,1,-0.0,-0.0,0,0,1,0,0
Swarm of Centipedes,22,19.2,-2.8,-0.0,2.0,-1.5,-0.0,-0.0,0.0,-8.4,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Warhorse Skeleton,22,21.2,-0.8,-1.5,-4.0,-2.2,-0.0,-0.0,0.0,-0.0,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Darkmantle,22,22.3,0.3,1.5,-2.0,1.1,-3.5,-1.5,0.0,-0.0,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Magma Mephit,22,23.0,1.0,-1.5,2.0,-4.5,3.5,-1.5,1.0,-0.0,...,0,1,0,-0.0,-0.0,0,0,0,0,0
Zombie,22,24.4,2.4,4.5,-0.0,0.4,-0.0,-0.0,0.0,-0.0,...,0,0,0,-0.0,-0.0,1,0,0,0,0
Swarm of Insects,22,25.1,3.1,-0.0,2.0,-1.5,-0.0,-0.0,0.0,-8.4,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Swarm of Spiders,22,25.1,3.1,-0.0,2.0,-1.5,-0.0,-0.0,0.0,-8.4,...,0,0,0,-0.0,-0.0,0,1,0,1,1
Swarm of Beetles,22,25.1,3.1,-0.0,2.0,-1.5,-0.0,-0.0,0.0,-8.4,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Swarm of Wasps,22,25.1,3.1,-0.0,2.0,-1.5,-0.0,-0.0,0.0,-8.4,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Lizardfolk,22,26.2,4.2,-4.5,-0.0,-2.2,-0.0,-0.0,0.0,-0.0,...,1,0,0,-0.0,-0.0,0,0,0,0,0
Sahuagin,22,27.8,5.8,-0.0,-6.0,0.8,-0.0,-0.0,0.0,-0.0,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Gray Ooze,22,28.8,6.8,6.0,2.0,-2.6,-0.0,-0.0,0.0,-9.6,...,0,0,0,-0.0,-0.0,0,0,0,0,0
Gnoll,22,28.9,6.9,-4.5,-0.0,0.4,-0.0,-0.0,0.0,-0.0,...,0,0,0,-0.0,-1.5,0,0,0,0,0
Reef Shark,22,32.1,10.1,-0.0,-2.0,1.1,-0.0,-0.0,0.0,-0.0,...,0,0,0,-2.0,-0.0,0,0,0,0,0

================================================================================
cr2 | actual_hp=59 | 5 creatures | pred range: 19.5 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-2.50],attack_deviation [×-3.00],dpr_deviation [×-1.00],f_false_appearance [no cost],f_keen_senses [no cost]
Name,,,,,,,,
Griffon,59,52.6,-6.4,2.5,-3.0,-2.5,0,1
Pegasus,59,56.1,-2.9,-2.5,-3.0,6.0,0,0
Ogre,59,61.6,2.6,5.0,-3.0,4.0,0,0
Awakened Tree,59,62.2,3.2,-0.0,-3.0,2.5,1,0
Owlbear,59,72.1,13.1,-0.0,-6.0,-1.5,0,1

================================================================================
cr1 | actual_hp=9 | 5 creatures | pred range: 15.8 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],resist+immun penalty,f_death_burst [no cost],f_keen_senses [no cost],f_spellcasting [no cost]
Name,,,,,,,,,,,
Giant Weasel,9,4.6,-4.4,-3.0,-4.0,-1.9,-0.0,-0.0,0,1,0
Noble,9,5.6,-3.4,-6.0,-0.0,-1.9,-0.0,-0.0,0,0,0
Cultist,9,9.0,0.0,-1.5,-0.0,-1.1,-0.0,-0.0,0,0,0
Acolyte,9,15.2,6.2,1.5,1.0,0.4,-3.5,-0.0,0,0,1
Magmin,9,20.4,11.4,-3.0,-0.0,-5.4,3.5,-7.0,1,0,0

================================================================================
cr1 | actual_hp=1 | 11 creatures | pred range: 12.6 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],resist+immun penalty,f_amphibious [no cost],f_blood_frenzy [-8.0],f_echolocation [no cost],f_flyby [no cost],f_keen_senses [no cost],f_mimicry [no cost],f_spider_climb [no cost],f_standing_leap [no cost],f_web_sense [no cost],f_web_walker [no cost]
Name,,,,,,,,,,,,,,,,,,
Quipper,1,-4.6,-5.6,-4.5,-14.0,0.8,-0.0,9.9,0,-8.0,0,0,0,0,0,0,0,0
Hawk,1,-2.6,-3.6,-4.5,-6.0,0.8,-0.0,3.9,0,-0.0,0,0,1,0,0,0,0,0
Weasel,1,-2.6,-3.6,-4.5,-6.0,0.8,-0.0,3.9,0,-0.0,0,0,1,0,0,0,0,0
Raven,1,-1.8,-2.8,-3.0,-4.0,0.8,-0.0,1.3,0,-0.0,0,0,0,1,0,0,0,0
Spider,1,-1.4,-2.4,-3.0,-4.0,-1.1,3.5,0.1,0,-0.0,0,0,0,0,1,0,1,1
Owl,1,0.4,-0.6,-1.5,-2.0,0.8,-0.0,-0.0,0,-0.0,0,1,1,0,0,0,0,0
Scorpion,1,2.5,1.5,-1.5,-0.0,-2.6,3.5,-0.0,0,-0.0,0,0,0,0,0,0,0,0
Bat,1,4.9,3.9,-3.0,4.0,0.8,-0.0,-0.0,0,-0.0,1,0,1,0,0,0,0,0
Sea Horse,1,7.2,6.2,-1.5,4.0,1.5,-0.0,-0.0,0,-0.0,0,0,0,0,0,0,0,0
Frog,1,7.2,6.2,-1.5,4.0,1.5,-0.0,-0.0,1,-0.0,0,0,0,0,0,1,0,0
Rat,1,7.9,6.9,-0.0,4.0,0.8,-0.0,-0.0,0,-0.0,0,0,1,0,0,0,0,0

================================================================================
cr1 | actual_hp=5 | 6 creatures | pred range: 12.3 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],has_disadvantage_condition [×+1.00],inflicts_prone [×-0.75],resist+immun penalty,f_flyby [no cost],f_keen_senses [no cost],f_pack_tactics [-2.0],f_sunlight_sensitivity [no cost]
Name,,,,,,,,,,,,,
Homunculus,5,-2.1,-7.1,-4.5,-4.0,0.8,0.0,-0.0,2.4,0,0,-0.0,0
Flying Snake,5,-1.6,-6.6,-4.5,-6.0,-4.1,0.0,-0.0,0.8,1,0,-0.0,0
Hyena,5,-0.0,-5.0,-1.5,-2.0,-1.1,0.0,-0.0,0.1,0,0,-2.0,0
Vulture,5,2.1,-2.9,-0.0,-2.0,-0.4,0.0,-0.0,-0.0,0,1,-2.0,0
Kobold,5,7.2,2.2,-1.5,-4.0,-1.1,1.0,-0.0,-0.0,0,0,-2.0,1
Mastiff,5,10.1,5.1,-1.5,-0.0,-1.1,0.0,-0.8,-0.0,0,1,-0.0,0

================================================================================
cr1 | actual_hp=7 | 5 creatures | pred range: 11.9 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],resist+immun penalty,f_keen_senses [no cost],f_magic_resistance [-3.0],f_nimble_escape [-14.0],f_pack_tactics [-2.0]
Name,,,,,,,,,,,,
Goblin,7,-1.4,-8.4,-12.0,-10.0,-0.4,-0.0,2.2,0,-0.0,-14.0,-0.0
Giant Rat,7,6.2,-0.8,-1.5,-4.0,-1.1,-0.0,-0.0,1,-0.0,-0.0,-2.0
Blood Hawk,7,6.2,-0.8,-1.5,-4.0,-1.1,-0.0,-0.0,1,-0.0,-0.0,-2.0
Diseased Giant Rat,7,9.7,2.7,-1.5,-4.0,-1.1,3.5,-0.0,1,-0.0,-0.0,-2.0
Pseudodragon,7,10.5,3.5,-6.0,-2.0,0.4,-0.0,-0.0,1,-3.0,-0.0,-0.0

================================================================================
cr1 | actual_hp=2 | 6 creatures | pred range: 6.4 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],save_dc_deviation [×-3.50],f_amphibious [no cost],f_invisibility [-1.5],f_keen_senses [no cost]
Name,,,,,,,,,,
Stirge,2,1.8,-0.2,-4.5,-4.0,-1.9,-0.0,0,-0.0,0
Cat,2,4.9,2.9,-3.0,4.0,0.8,-0.0,0,-0.0,1
Poisonous Snake,2,6.4,4.4,-3.0,-4.0,-2.2,3.5,0,-0.0,0
Crab,2,6.4,4.4,-1.5,4.0,0.8,-0.0,1,-0.0,0
Lizard,2,7.9,5.9,-0.0,4.0,0.8,-0.0,0,-0.0,0
Sprite,2,8.2,6.2,-10.5,-6.0,3.0,3.5,0,-1.5,0

================================================================================
cr1 | actual_hp=3 | 5 creatures | pred range: 5.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],resist+immun penalty,f_hold_breath [no cost],f_keen_senses [no cost],f_pack_tactics [-2.0],f_terrain_camouflage [no cost]
Name,,,,,,,,,,,
Eagle,3,-1.8,-4.8,-3.0,-4.0,-1.9,3.3,0,1,-0.0,0
Octopus,3,-1.1,-4.1,-3.0,-4.0,0.8,1.3,1,0,-0.0,1
Baboon,3,-0.3,-3.3,-3.0,-0.0,-1.1,-0.0,0,0,-2.0,0
Jackal,3,-0.3,-3.3,-3.0,-0.0,-1.1,-0.0,0,1,-2.0,0
Badger,3,3.9,0.9,-0.0,-0.0,0.8,-0.0,0,1,-0.0,0

================================================================================
cr1 | actual_hp=4 | 5 creatures | pred range: 4.7 HP
================================================================================

,actual_hp,predicted_hp,hp_delta,ac_deviation [×-1.50],attack_deviation [×-2.00],dpr_deviation [×-0.75],inflicts_prone [×-0.75],resist+immun penalty,f_charge [no cost],f_illumination [no cost],f_sure_footed [no cost]
Name,,,,,,,,,,,
Giant Fire Beetle,4,-0.5,-4.5,-4.5,2.0,-1.9,-0.0,-0.0,0,1,0
Deer,4,-0.1,-4.1,-4.5,-0.0,-0.4,-0.0,0.3,0,0,0
Giant Centipede,4,0.4,-3.6,-3.0,-2.0,-7.5,-0.0,-0.0,0,0,0
Goat,4,0.6,-3.4,-0.0,-2.0,-1.1,-0.8,-0.0,1,0,1
Commoner,4,4.1,0.1,-0.0,-0.0,-0.4,-0.0,-0.0,0,0,0